### ISSUE TITLE
Unable to connect to websocket API

### ISSUE THREAD

**Issue by arniecommits** [volumio/volumio3-backend#202]
python3 test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    sio.connect('http://127.0.0.1:3000')
  File "/home/volumio/.local/lib/python3.7/site-packages/socketio/client.py", line 148, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: OPEN packet not returned by server

This is causing several plugins that rely on this to fail

**Comment by pettarin** [comment]
@arniecommits : what version of `python-socketio` are you using?

In a virtual environment with:

```
$ pip list | grep socketio
python-socketio    4.6.1
```

The following minimal test script works for me (Volumio 4.119):

```bash
$ cat test.py
import socketio
sio = socketio.Client()
sio.connect("http://volumio:3000")       # change the host/port as needed
print("Connected", sio)
sio.disconnect()
print("Disconnected")

$ python test.py 
Connected <socketio.client.Client object at 0x7f7b35e01a90>
Disconnected
```

Bottom line: you need to pin `python-socketio>=4,<5` to match the SocketIO protocol used by Volumio, see the "Version compatibility" in https://pypi.org/project/python-socketio/

**Comment by pettarin** [comment]
See also https://github.com/pettarin/volumito/blob/main/pyproject.toml#L58 --- `volumito` exercises heavily the WebSocket API of Volumio and I have never found problems connecting to it.
